[tool.black]
line-length = 120
target-version = ["py39", "py310", "py311", "py312"]

[tool.ruff]
line-length = 120
lint.ignore = ["E741"]

[tool.ruff.lint.per-file-ignores]
"test.py" = ["E501"]

[dependency-groups]
dev = [
    "wtpsplit>=2.1.7",
]
