[package]
name = "nnsplit"
version = "0.2.2"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

description = "Rust bindings for fast, robust sentence splitting using machine learning."
repository = "https://github.com/bminixhofer/nnsplit"
homepage = "https://github.com/bminixhofer/nnsplit"
documentation = "https://github.com/bminixhofer/nnsplit"
keywords = ["pytorch", "deep-learning", "machine-learning", "tokenizer", "sentencizer"]
categories = ["science"]
license = "MIT"
readme = "README.md"

include = ["src/*.rs", "tests/*.rs", "build.rs", "data"]

[dependencies]
failure = "0.1.6"
tch = "0.1.6"
ndarray = "0.13"

[build-dependencies]
failure = "0.1.6"
fs_extra = "1.1.0"

[dev-dependencies]
criterion = "0.3"

# [[bench]]
# name = "bench_nnsplit"
# harness = false
# path = "benches/bench_nnsplit.rs"