[package]
name = "nnsplit-python"
version = "0.4.1-post"
authors = ["Benjamin Minixhofer <bminixhofer@gmail.com>"]
edition = "2018"

[package.metadata.maturin]
requires-dist = ["onnxruntime>=1.4,<2"]

[lib]
name = "nnsplit"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.13"
numpy = "0.11.0"
lazy_static = "1.4"

[dependencies.nnsplit]
path = "../../nnsplit"
default-features =  false
features = ["model-loader"]

# this must be at the bottom due to hack to add extension-module feature in Makefile
# will be fixed by https://github.com/PyO3/pyo3/pull/1123
# newline at end of file is also needed :(
[dependencies.pyo3]
version = "=0.11.1"
