name: CI

on:
  release:
    types: [published]
  push:
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: read

jobs:
  build-javascript:
    runs-on: ubuntu-18.04
    env:
      working-directory: bindings/javascript
    strategy:
      matrix:
        browser: ["firefox", "chrome", "electron"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
      - name: Install wasm-pack # need a build from master for https://github.com/rustwasm/wasm-pack/pull/839
        run: cargo install --git https://github.com/rustwasm/wasm-pack --rev d46d1c6
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build module
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Run Node.js tests
        run: npm run test:node
        working-directory: ${{env.working-directory}}
      - name: Run Cypress tests
        uses: cypress-io/github-action@f5bea478b80a774068179089247f13d60abc5010 # v2.11.8
        with:
          working-directory: ${{env.working-directory}}
          start: npm run start_test_server
          wait-on: "http://localhost:8080"
          browser: ${{ matrix.browser }}

  build-rust:
    runs-on: ubuntu-18.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: Cache cargo registry
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3.2.5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3.2.5
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3.2.5
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: build
          args: --verbose
      - run: rustup component add clippy
      - run: cargo clippy --all-features
      - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: test
          args: --verbose --all-features

  build-python:
    runs-on: ${{ matrix.os }}
    env:
      working-directory: bindings/python
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@152ba7c4dd6521b8e9c93f72d362ce03bf6c4f20 # v1.2.3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install GSED (if needed) # needed by update_version.sh
        if: github.event_name == 'release' && matrix.os == 'macos-latest'
        run: |
          brew install gnu-sed
      - name: Update version (if release) # only needed for python since we store artifacts, others are rebuilt
        if: github.event_name == 'release'
        run: |
          bash update_version.sh ${{ github.event.release.tag_name }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          make install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: |
          make build
        working-directory: ${{env.working-directory}}
      - name: Test
        run: |
          make test
        working-directory: ${{env.working-directory}}
      - name: Upload wheel as artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: python-wheel
          path: bindings/python/target/wheels/*

  publish:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-18.04
    needs: [build-javascript, build-rust, build-python]
    if: github.event_name == 'release'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
        with:
          ref: ${{ github.head_ref }}
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
      - name: Install wasm-pack # need a build from master for https://github.com/rustwasm/wasm-pack/pull/839
        run: cargo install --git https://github.com/rustwasm/wasm-pack --rev d46d1c6
      - name: Set up Python 3.8
        uses: actions/setup-python@152ba7c4dd6521b8e9c93f72d362ce03bf6c4f20 # v1.2.3
        with:
          python-version: 3.8
      - run: |
          pip install twine==3.2
      - uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # v2.1.0
        with:
          name: python-wheel
          path: python-wheel
      - name: Update version
        run: |
          bash update_version.sh ${{ github.event.release.tag_name }}
      - name: Run release script
        run: |
          bash release.sh
        env:
          CARGO_KEY: ${{ secrets.CARGO_KEY }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          WHEEL_DIR: python-wheel
      - run: |
          rm -r python-wheel
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        with:
          commit_message: v${{ github.event.release.tag_name }}
          branch: main
