name: CI

on: [push]

jobs:
  python_ci:
    name: Python Library CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Install library
      working-directory: ./python_lib
      run: |
        source $HOME/.poetry/env
        make install
    - name: Run tests
      working-directory: ./python_lib
      run: |
        source $HOME/.poetry/env
        make test
  rust_ci:
    name: Rust Library CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --manifest-path ./rust_lib/Cargo.toml
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path ./rust_lib/Cargo.toml
